export const modules = [
  {
    id: 'm1',
    number: 1,
    title: 'Spring Basics',
    description: 'What springs actually do — and why that changes everything about how you program.',
    color: 'var(--color-module-1)',
    alwaysOpen: false,
    lessons: [
      { id: 'm1-l1', title: 'Springs 101', hasAnimation: false },
      { id: 'm1-l2', title: 'Spring Load vs. Constant Weight', hasAnimation: true },
      { id: 'm1-l3', title: 'Spring Design Basics', hasAnimation: false },
      { id: 'm1-l4', title: 'Spring Wear and Lifespan', hasAnimation: false },
      { id: 'm1-l5', title: 'Pretensioning Springs', hasAnimation: false },
      { id: 'm1-quiz', title: 'Assessment Quiz', hasAnimation: false, isAssessment: true },
    ],
  },
  {
    id: 'm2',
    number: 2,
    title: 'Springs, Settings, and Bodies',
    description: 'How height, weight, and equipment configuration change the actual force a client experiences.',
    color: 'var(--color-module-2)',
    alwaysOpen: false,
    requiredModule: 'm1',
    lessons: [
      { id: 'm2-l1', title: 'Height and Spring Load', hasAnimation: true },
      { id: 'm2-l2', title: 'Body Weight, Friction, and Gravity', hasAnimation: false },
      { id: 'm2-l3', title: 'Rope Adjustments: Short vs. Long Loops', hasAnimation: false },
      { id: 'm2-l4', title: 'Supportive vs. Resistive Spring Behavior', hasAnimation: false },
      { id: 'm2-quiz', title: 'Assessment', hasAnimation: false, isAssessment: true },
    ],
  },
  {
    id: 'm3',
    number: 3,
    title: 'The Physics of Different Movement',
    description: 'Force vectors, planes of movement, and why the same spring setting means different things on different exercises.',
    color: 'var(--color-module-3)',
    alwaysOpen: false,
    requiredModule: 'm2',
    lessons: [
      { id: 'm3-l1', title: 'Understanding Force Vectors', hasAnimation: false },
      { id: 'm3-l2', title: 'Standing vs. Seated Reformer', hasAnimation: false },
      { id: 'm3-l3', title: 'Pulley Height', hasAnimation: false },
      { id: 'm3-l4', title: 'Plank / Pike', hasAnimation: false },
      { id: 'm3-quiz', title: 'Final Assessment', hasAnimation: false, isAssessment: true },
    ],
  },
  {
    id: 'm4',
    number: 4,
    title: 'Advanced Physics Portal',
    description: 'Self-directed, always open. Deeper dives into chair physics, Cadillac mechanics, and angular velocity.',
    color: 'var(--color-module-4)',
    alwaysOpen: true,
    lessons: [
      { id: 'm4-l1', title: 'Angular Velocity', hasAnimation: false },
      { id: 'm4-l2', title: 'Chair Physics', hasAnimation: false },
      { id: 'm4-l3', title: 'Cadillac Physics', hasAnimation: false },
    ],
  },
]
